"""A secret vehicle code is generated by the following steps:

Extracting the first 2 letters from the name
Converting the 2 letters to uppercase
Join the 2 letters with the last 3 letters

For a given vehicle_name, generate and print the secret code

Complete the given program"""

vehicle_name='niaLmEdystProgRammerhvvdvkjhoillhdsiolksdluvsdkjhlkdiufdjkkvdsoajckvuskcnkjasdvkknkdfjnja'

print("NInja")
